### ISSUE TITLE
Additional maintainer needed?

### ISSUE THREAD

**Issue by lhaussknecht** [nexusforge/unifi-docker#1]
Hey there,

I'm using this fork of unifi-docker in my setup, since jacobalberty/unifi-docker is not maintained anyomere.

I would be happy to contribute and be a maintainer. In this way we can make sure, that at least two people have write access to the repo.

What do you think?

**Comment by arkste** [comment]
sure. i'm open for additional maintainers, but this would require at least one PR :)
