### ISSUE TITLE
Using Podman with this repo

### ISSUE THREAD

**Issue by simpz** [nexusforge/unifi-docker#2]
I tried to follow the instructions to switch to here from jacobalberty/unifi:
```
controller:
    #image: "jacobalberty/unifi:${TAG:-latest}"
    image: "nexusforge/unifi-docker:${TAG:-latest}"
```
In podman I have added, which I thought would be correct.
unqualified-search-registries = ["github.com"]
to  /etc/containers/registries.conf

This still doesn't allow me to pull. 

```
Resolving "nexusforge/unifi-docker" using unqualified-search registries (/etc/containers/registries.conf)
Trying to pull github.com/nexusforge/unifi-docker:latest...
Error: initializing source docker://github.com/nexusforge/unifi-docker:latest: reading manifest latest in github.com/nexusforge/unifi-docker: StatusCode: 404, Not Found
```
So I guess my unqualified-search-registries is wrong. Any idea what this should be or a fully qualified path that docker:// needs for this repo.

**Comment by ludacrash** [comment]
I see yo are trying to pull it from GitHub while it has been deployed/released to Docker Hub. So if you would pull it from Docker hub it should work.

**Comment by simpz** [comment]
I'm being silly on this, fully qualifying now works great with podman.
docker.io/nexusforge/unifi-docker

Thank you so so much for maintaining this.
