### ISSUE TITLE
Release 8.6.9 looks broken?

### ISSUE THREAD

**Issue by simpz** [nexusforge/unifi-docker#3]
The new release seems to be broken for me. 
It fails with a glibc error and eventually mongo-db gets an OoM...
It never starts.

```
Nov 08 00:14:08 podhost unifi[1861836]: permset: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by permset)
Nov 08 00:14:08 podhost unifi[1861836]: permset: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by permset)
Nov 08 00:14:08 podhost unifi[1861836]: [2024-11-08 00:14:08,506] <docker-entrypoint> Starting unifi controller service.
Nov 08 01:54:34 podhost unifi[1861836]: [6025.628s][warning][os,thread] Failed to start thread "Unknown thread" - pthread_create failed (EAGAIN) for attributes: s>
Nov 08 01:54:34 podhost unifi[1861836]: [6025.628s][warning][os,thread] Failed to start the native thread for java.lang.Thread "crash-reporter"
Nov 08 01:54:34 podhost unifi[1861836]: Exception in thread "mongo-db" java.lang.OutOfMemoryError: unable to create native thread: possibly out of memory or proce>
Nov 08 01:54:34 podhost unifi[1861836]:         at java.base/java.lang.Thread.start0(Native Method)
Nov 08 01:54:34 podhost unifi[1861836]:         at java.base/java.lang.Thread.start(Thread.java:809)
```

**Comment by arkste** [comment]
Internesting, which platform? amd64 or arm? 

Its working for me on amd64, but it seems to be related to the permset change i did.

I've [reverted the change](https://github.com/nexusforge/unifi-docker/commit/754a1ec82c001b68a9b448741fa9e96d5d05c184) and re-relased the image. 

Can you please test again? Thanks.

**Comment by simpz** [comment]
That's weirdly still broken.
The host system this is running on is an amd64 system running Debian 12 on podman.

```
Nov 08 15:42:10 podhost podman[2310960]: 2024-11-08 15:42:10.22760645 +0000 GMT m=+0.324476936 container start 73444537f587261482ff295b698df2f6135eb5d8f394443af60981af7d1197d5 (image=docker.io/nexusforge/unifi-docker:latest, name=unifi, maintainer=https://github.com/nexusforge, nexusforge/unifi-docker:v8.6=, org.opencontainers.image.version=20.04, nexusforge/unifi-docker:v8.6.9=, org.opencontainers.image.ref.name=ubuntu, nexusforge/unifi-docker:latest=, nexusforge/unifi-docker:v8=, io.containers.autoupdate=registry, PODMAN_SYSTEMD_UNIT=container-unifi.service)
Nov 08 15:42:10 podhost podman[2310960]: 73444537f587261482ff295b698df2f6135eb5d8f394443af60981af7d1197d5
Nov 08 15:42:10 podhost unifi[2311343]: permset: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by permset)
Nov 08 15:42:10 podhost unifi[2311343]: permset: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by permset)
Nov 08 15:42:10 podhost unifi[2311343]: [2024-11-08 15:42:10,234] <docker-entrypoint> Starting unifi controller service.

```
This is the startup from the unit file incase that helps.
```

ExecStart=/usr/bin/podman run \
        --cidfile=%t/%n.ctr-id \
        --cgroups=no-conmon \
        --rm \
        --sdnotify=conmon \
        --cap-add=CAP_NET_RAW \
        --replace \
        -d \
        --init \
        -p 8080:8080 \
        -p 8443:8443 \
        -p 3478:3478/udp \
        -e TZ=Europe/London \
        -e UMASK=0077 \
        -v /home/unifiappli/data:/unifi \
        --user 1012:1012 \
        --network podman3 \
        --label "io.containers.autoupdate=registry" \
        --name unifi docker.io/nexusforge/unifi-docker:latest
```

**Comment by arkste** [comment]
i've setup a fresh debian 12 machine with docker and the image works fine.
my guess is that there's an issue somewhere else, but not in the image.

unfortunately there's nothing else i can do, sorry.

**Comment by thaggren** [comment]
Just for reference, "FROM golang:1.23-bookworm as permset" works fine on Ubuntu 24.04.1 LTS / kernel 6.8.0-1015-azure.

**Comment by arkste** [comment]
yeah, saw the same before releasing the image, but wanted to make sure. 

will include the golang upgrade in the next release again.

**Comment by thaggren** [comment]
Great, thanks :)

**Comment by simpz** [comment]
There is something weird about this. My main system is an AMD system:
```
1012@181118ebef26:~$ ldd /usr/local/bin/permset 
/usr/local/bin/permset: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /usr/local/bin/permset)
/usr/local/bin/permset: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /usr/local/bin/permset)
	linux-vdso.so.1 (0x00007ffe47aac000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007faed14ff000)
	/lib64/ld-linux-x86-64.so.2 (0x00007faed16f7000)

```
Where as inside the test podman VM I have on an Intel system looks happy with this and unifi starts fine:

```
1012@8c74b923c42d:~$ ldd /usr/local/bin/permset 
	linux-vdso.so.1 (0x00007fff8cb88000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f02427bb000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f0242798000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f02429b3000)
```

libc code path different with a different CPU?
This is kind of similar:
https://github.com/mattermost-community/focalboard/issues/4770

**Comment by simpz** [comment]
Not complaining but just as a data point, the original jacobalberty/unifi-docker 8.6.9 (which I think you forked from?), works on my AMD system perfectly.

**Comment by arkste** [comment]
no, thats totally fine, but still very interesting. 

i will take a more deeply look into it tomorrow, but the Dockerfile is basically the same:

```diff
$ git diff unifi-docker-jacobalberty/Dockerfile unifi-docker-nexusforge/Dockerfile
diff --git a/unifi-docker-jacobalberty/Dockerfile b/unifi-docker-nexusforge/Dockerfile
index 8d255ab..e34923d 100644
--- a/unifi-docker-jacobalberty/Dockerfile
+++ b/unifi-docker-nexusforge/Dockerfile
@@ -1,12 +1,12 @@
 FROM golang:1.22-bullseye as permset
 WORKDIR /src
-RUN git clone https://github.com/jacobalberty/permset.git /src && \
+RUN git clone https://github.com/nexusforge/permset.git /src && \
     mkdir -p /out && \
     go build -ldflags "-X main.chownDir=/unifi" -o /out/permset

 FROM ubuntu:20.04

-LABEL maintainer="Jacob Alberty <jacob.alberty@foundigital.com>"
+LABEL maintainer="https://github.com/nexusforge"

 ARG DEBIAN_FRONTEND=noninteractive
```

**Comment by simpz** [comment]
Using "podman build" on a checked out copy of your repo gives me a working image on this system.
Curious indeed.....

**Comment by simpz** [comment]
I build your image on the Intel system (well Debian VM) where your image did work on podman and transferred this image back to the AMD system and that image also works fine. Which makes me think there is something about the build system you are using for these images (maybe just this time)? Anything unusual about this or something that can be configured....that's all I can see now. Unless you have any more thoughts?

**Comment by arkste** [comment]
i've tested quite a bit, but i really cant find the reason why its not working for you.

the build-system is github's workflows, see here:
https://github.com/nexusforge/unifi-docker/tree/master/.github/workflows

its the same as the original repository. they recently only changed how the labels are populated, but the core is the same.

**Comment by simpz** [comment]
Yup the two build look pretty similar (i.e. vs jacobalberty) I don't get it....
I might stop all the containers on this host, flush all images (in case a layering issue) and restart.
I guess I'll see on the next release what happens...
Thanks for looking.
